#: import os os
<MenuLayout>:

<MainActivity>:
    BoxLayout:
        orientation: "vertical"
        ScrollView:
            BoxLayout:
                orientation: "vertical"
                size_hint_y: None
                height: self.minimum_height
                BoxLayout:
                    id: body
                    size_hint_y: None
                    height: self.minimum_height
                    orientation: "vertical"
                BoxLayout:

        Button:
            text: "Add"
            size_hint_y: None
            height: dp(40)



<BottomLayout>:

<AddMealScreen>:
    body: body
    BoxLayout:
        id: body
        orientation: "vertical"
        LabelTextInput:
            name: "Название"
        BoxLayout:
            id: empty_spacing
        BoxLayout:
            BoxLayout:
            Button:
                text: "+"
                size_hint: None, None
                size: dp(50), dp(50)
                on_release: root.add_line()
        Button:
            text: "Добавить блюдо"
            size_hint: 1, None
            height: dp(50)
            on_release: root.save()





<RTextInput>:
    



<MainLayout>:
    orientation: "vertical"
    MenuLayout:
        size_hint_y: None
        height: dp(50)
    MainActivity:
        id: main_activity
    BottomLayout:
        size_hint_y: None
        height: dp(50)


<LabelTextInput>:
    size_hint_y: None
    height: dp(40)
    Label:
        text: root.name
    RTextInput:
        id: text
    RTextInput:
        id: quant

<DayLine>:
    size_hint_y: None
    height: dp(80)
    orientation: "vertical"
    BoxLayout:

        Label:
            text: root.value.get("date")
        Label:
            text: root.value.get("calories", 0)
    BoxLayout:
        BoxLayout:
            size_hint_x: None
            width: dp(5)
        Image:
            source: os.path.join("assets", "meat.png")
            size: dp(15), dp(15)
        Label:
            text: root.value.get("proteins", 0)
            size_hint: None, None
            size: dp(15), dp(15)
        Image:
            source: os.path.join("assets", "fat.png")
            size: dp(15), dp(15)
        Label:
            text: root.value.get("fats", 0)
            size_hint: None, None
            size: dp(15), dp(15)
        Image:
            source: os.path.join("assets", "carboh.png")
            size: dp(15), dp(15)
        Label:
            text: root.value.get("carboh", 0)
            size_hint: None, None
            size: dp(15), dp(15)
        Button:
            text: "...>"